package cn.edu.fudan.se.cochange_analysis.git.bean;

import java.io.Serializable;

public class AccumutiveBug extends AccumutiveBugKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumutive_bug.rank
     *
     * @mbg.generated
     */
    private Integer rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumutive_bug.bug_frequency
     *
     * @mbg.generated
     */
    private Integer bugFrequency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accumutive_bug.bug_churn
     *
     * @mbg.generated
     */
    private Integer bugChurn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table accumutive_bug
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumutive_bug
     *
     * @mbg.generated
     */
    public AccumutiveBug(Integer repositoryId, String fileName, Integer rank, Integer bugFrequency, Integer bugChurn) {
        super(repositoryId, fileName);
        this.rank = rank;
        this.bugFrequency = bugFrequency;
        this.bugChurn = bugChurn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumutive_bug
     *
     * @mbg.generated
     */
    public AccumutiveBug() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumutive_bug.rank
     *
     * @return the value of accumutive_bug.rank
     *
     * @mbg.generated
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumutive_bug.rank
     *
     * @param rank the value for accumutive_bug.rank
     *
     * @mbg.generated
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumutive_bug.bug_frequency
     *
     * @return the value of accumutive_bug.bug_frequency
     *
     * @mbg.generated
     */
    public Integer getBugFrequency() {
        return bugFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumutive_bug.bug_frequency
     *
     * @param bugFrequency the value for accumutive_bug.bug_frequency
     *
     * @mbg.generated
     */
    public void setBugFrequency(Integer bugFrequency) {
        this.bugFrequency = bugFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accumutive_bug.bug_churn
     *
     * @return the value of accumutive_bug.bug_churn
     *
     * @mbg.generated
     */
    public Integer getBugChurn() {
        return bugChurn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accumutive_bug.bug_churn
     *
     * @param bugChurn the value for accumutive_bug.bug_churn
     *
     * @mbg.generated
     */
    public void setBugChurn(Integer bugChurn) {
        this.bugChurn = bugChurn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumutive_bug
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AccumutiveBug other = (AccumutiveBug) that;
        return (this.getRepositoryId() == null ? other.getRepositoryId() == null : this.getRepositoryId().equals(other.getRepositoryId()))
            && (this.getFileName() == null ? other.getFileName() == null : this.getFileName().equals(other.getFileName()))
            && (this.getRank() == null ? other.getRank() == null : this.getRank().equals(other.getRank()))
            && (this.getBugFrequency() == null ? other.getBugFrequency() == null : this.getBugFrequency().equals(other.getBugFrequency()))
            && (this.getBugChurn() == null ? other.getBugChurn() == null : this.getBugChurn().equals(other.getBugChurn()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumutive_bug
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRepositoryId() == null) ? 0 : getRepositoryId().hashCode());
        result = prime * result + ((getFileName() == null) ? 0 : getFileName().hashCode());
        result = prime * result + ((getRank() == null) ? 0 : getRank().hashCode());
        result = prime * result + ((getBugFrequency() == null) ? 0 : getBugFrequency().hashCode());
        result = prime * result + ((getBugChurn() == null) ? 0 : getBugChurn().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accumutive_bug
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rank=").append(rank);
        sb.append(", bugFrequency=").append(bugFrequency);
        sb.append(", bugChurn=").append(bugChurn);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}