package cn.edu.fudan.se.cochange_analysis.git.bean;

import java.io.Serializable;
import java.util.Date;

public class BugFixFile extends BugFixFileKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bug_fix_file.line_of_code
     *
     * @mbg.generated
     */
    private Integer lineOfCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bug_fix_file.fix_date
     *
     * @mbg.generated
     */
    private Date fixDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bug_fix_file
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bug_fix_file
     *
     * @mbg.generated
     */
    public BugFixFile(Integer repositoryId, String commitId, String fileName, String shortName, String issueId, Integer lineOfCode, Date fixDate) {
        super(repositoryId, commitId, fileName, shortName, issueId);
        this.lineOfCode = lineOfCode;
        this.fixDate = fixDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bug_fix_file
     *
     * @mbg.generated
     */
    public BugFixFile() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bug_fix_file.line_of_code
     *
     * @return the value of bug_fix_file.line_of_code
     *
     * @mbg.generated
     */
    public Integer getLineOfCode() {
        return lineOfCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bug_fix_file.line_of_code
     *
     * @param lineOfCode the value for bug_fix_file.line_of_code
     *
     * @mbg.generated
     */
    public void setLineOfCode(Integer lineOfCode) {
        this.lineOfCode = lineOfCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bug_fix_file.fix_date
     *
     * @return the value of bug_fix_file.fix_date
     *
     * @mbg.generated
     */
    public Date getFixDate() {
        return fixDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bug_fix_file.fix_date
     *
     * @param fixDate the value for bug_fix_file.fix_date
     *
     * @mbg.generated
     */
    public void setFixDate(Date fixDate) {
        this.fixDate = fixDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bug_fix_file
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BugFixFile other = (BugFixFile) that;
        return (this.getRepositoryId() == null ? other.getRepositoryId() == null : this.getRepositoryId().equals(other.getRepositoryId()))
            && (this.getCommitId() == null ? other.getCommitId() == null : this.getCommitId().equals(other.getCommitId()))
            && (this.getFileName() == null ? other.getFileName() == null : this.getFileName().equals(other.getFileName()))
            && (this.getShortName() == null ? other.getShortName() == null : this.getShortName().equals(other.getShortName()))
            && (this.getIssueId() == null ? other.getIssueId() == null : this.getIssueId().equals(other.getIssueId()))
            && (this.getLineOfCode() == null ? other.getLineOfCode() == null : this.getLineOfCode().equals(other.getLineOfCode()))
            && (this.getFixDate() == null ? other.getFixDate() == null : this.getFixDate().equals(other.getFixDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bug_fix_file
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRepositoryId() == null) ? 0 : getRepositoryId().hashCode());
        result = prime * result + ((getCommitId() == null) ? 0 : getCommitId().hashCode());
        result = prime * result + ((getFileName() == null) ? 0 : getFileName().hashCode());
        result = prime * result + ((getShortName() == null) ? 0 : getShortName().hashCode());
        result = prime * result + ((getIssueId() == null) ? 0 : getIssueId().hashCode());
        result = prime * result + ((getLineOfCode() == null) ? 0 : getLineOfCode().hashCode());
        result = prime * result + ((getFixDate() == null) ? 0 : getFixDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bug_fix_file
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lineOfCode=").append(lineOfCode);
        sb.append(", fixDate=").append(fixDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}