package cn.edu.fudan.se.cochange_analysis.git.bean;

import java.io.Serializable;

public class ChangeRelationKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_relation.repository_id
     *
     * @mbg.generated
     */
    private Integer repositoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_relation.file_name1
     *
     * @mbg.generated
     */
    private String fileName1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_relation.file_name2
     *
     * @mbg.generated
     */
    private String fileName2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_relation.change_type1
     *
     * @mbg.generated
     */
    private String changeType1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_relation.change_type2
     *
     * @mbg.generated
     */
    private String changeType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table change_relation
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_relation
     *
     * @mbg.generated
     */
    public ChangeRelationKey(Integer repositoryId, String fileName1, String fileName2, String changeType1, String changeType2) {
        this.repositoryId = repositoryId;
        this.fileName1 = fileName1;
        this.fileName2 = fileName2;
        this.changeType1 = changeType1;
        this.changeType2 = changeType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_relation
     *
     * @mbg.generated
     */
    public ChangeRelationKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_relation.repository_id
     *
     * @return the value of change_relation.repository_id
     *
     * @mbg.generated
     */
    public Integer getRepositoryId() {
        return repositoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_relation.repository_id
     *
     * @param repositoryId the value for change_relation.repository_id
     *
     * @mbg.generated
     */
    public void setRepositoryId(Integer repositoryId) {
        this.repositoryId = repositoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_relation.file_name1
     *
     * @return the value of change_relation.file_name1
     *
     * @mbg.generated
     */
    public String getFileName1() {
        return fileName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_relation.file_name1
     *
     * @param fileName1 the value for change_relation.file_name1
     *
     * @mbg.generated
     */
    public void setFileName1(String fileName1) {
        this.fileName1 = fileName1 == null ? null : fileName1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_relation.file_name2
     *
     * @return the value of change_relation.file_name2
     *
     * @mbg.generated
     */
    public String getFileName2() {
        return fileName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_relation.file_name2
     *
     * @param fileName2 the value for change_relation.file_name2
     *
     * @mbg.generated
     */
    public void setFileName2(String fileName2) {
        this.fileName2 = fileName2 == null ? null : fileName2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_relation.change_type1
     *
     * @return the value of change_relation.change_type1
     *
     * @mbg.generated
     */
    public String getChangeType1() {
        return changeType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_relation.change_type1
     *
     * @param changeType1 the value for change_relation.change_type1
     *
     * @mbg.generated
     */
    public void setChangeType1(String changeType1) {
        this.changeType1 = changeType1 == null ? null : changeType1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_relation.change_type2
     *
     * @return the value of change_relation.change_type2
     *
     * @mbg.generated
     */
    public String getChangeType2() {
        return changeType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_relation.change_type2
     *
     * @param changeType2 the value for change_relation.change_type2
     *
     * @mbg.generated
     */
    public void setChangeType2(String changeType2) {
        this.changeType2 = changeType2 == null ? null : changeType2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_relation
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ChangeRelationKey other = (ChangeRelationKey) that;
        return (this.getRepositoryId() == null ? other.getRepositoryId() == null : this.getRepositoryId().equals(other.getRepositoryId()))
            && (this.getFileName1() == null ? other.getFileName1() == null : this.getFileName1().equals(other.getFileName1()))
            && (this.getFileName2() == null ? other.getFileName2() == null : this.getFileName2().equals(other.getFileName2()))
            && (this.getChangeType1() == null ? other.getChangeType1() == null : this.getChangeType1().equals(other.getChangeType1()))
            && (this.getChangeType2() == null ? other.getChangeType2() == null : this.getChangeType2().equals(other.getChangeType2()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_relation
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRepositoryId() == null) ? 0 : getRepositoryId().hashCode());
        result = prime * result + ((getFileName1() == null) ? 0 : getFileName1().hashCode());
        result = prime * result + ((getFileName2() == null) ? 0 : getFileName2().hashCode());
        result = prime * result + ((getChangeType1() == null) ? 0 : getChangeType1().hashCode());
        result = prime * result + ((getChangeType2() == null) ? 0 : getChangeType2().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_relation
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", repositoryId=").append(repositoryId);
        sb.append(", fileName1=").append(fileName1);
        sb.append(", fileName2=").append(fileName2);
        sb.append(", changeType1=").append(changeType1);
        sb.append(", changeType2=").append(changeType2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}