package cn.edu.fudan.se.cochange_analysis.git.bean;

import java.io.Serializable;

public class ChangeOperationWithBLOBs extends ChangeOperation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_operation.root_entity_content
     *
     * @mbg.generated
     */
    private String rootEntityContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_operation.parent_entity_content
     *
     * @mbg.generated
     */
    private String parentEntityContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_operation.changed_entity_content
     *
     * @mbg.generated
     */
    private String changedEntityContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_operation.new_entity_content
     *
     * @mbg.generated
     */
    private String newEntityContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table change_operation
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_operation
     *
     * @mbg.generated
     */
    public ChangeOperationWithBLOBs(Integer changeOperationId, Integer repositoryId, String commitId, String fileName, String rootEntityType, String parentEntityType, String changeType, String significanceLevel, String changedEntityType, String rootEntityContent, String parentEntityContent, String changedEntityContent, String newEntityContent) {
        super(changeOperationId, repositoryId, commitId, fileName, rootEntityType, parentEntityType, changeType, significanceLevel, changedEntityType);
        this.rootEntityContent = rootEntityContent;
        this.parentEntityContent = parentEntityContent;
        this.changedEntityContent = changedEntityContent;
        this.newEntityContent = newEntityContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_operation
     *
     * @mbg.generated
     */
    public ChangeOperationWithBLOBs() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_operation.root_entity_content
     *
     * @return the value of change_operation.root_entity_content
     *
     * @mbg.generated
     */
    public String getRootEntityContent() {
        return rootEntityContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_operation.root_entity_content
     *
     * @param rootEntityContent the value for change_operation.root_entity_content
     *
     * @mbg.generated
     */
    public void setRootEntityContent(String rootEntityContent) {
        this.rootEntityContent = rootEntityContent == null ? null : rootEntityContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_operation.parent_entity_content
     *
     * @return the value of change_operation.parent_entity_content
     *
     * @mbg.generated
     */
    public String getParentEntityContent() {
        return parentEntityContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_operation.parent_entity_content
     *
     * @param parentEntityContent the value for change_operation.parent_entity_content
     *
     * @mbg.generated
     */
    public void setParentEntityContent(String parentEntityContent) {
        this.parentEntityContent = parentEntityContent == null ? null : parentEntityContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_operation.changed_entity_content
     *
     * @return the value of change_operation.changed_entity_content
     *
     * @mbg.generated
     */
    public String getChangedEntityContent() {
        return changedEntityContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_operation.changed_entity_content
     *
     * @param changedEntityContent the value for change_operation.changed_entity_content
     *
     * @mbg.generated
     */
    public void setChangedEntityContent(String changedEntityContent) {
        this.changedEntityContent = changedEntityContent == null ? null : changedEntityContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_operation.new_entity_content
     *
     * @return the value of change_operation.new_entity_content
     *
     * @mbg.generated
     */
    public String getNewEntityContent() {
        return newEntityContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_operation.new_entity_content
     *
     * @param newEntityContent the value for change_operation.new_entity_content
     *
     * @mbg.generated
     */
    public void setNewEntityContent(String newEntityContent) {
        this.newEntityContent = newEntityContent == null ? null : newEntityContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_operation
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ChangeOperationWithBLOBs other = (ChangeOperationWithBLOBs) that;
        return (this.getChangeOperationId() == null ? other.getChangeOperationId() == null : this.getChangeOperationId().equals(other.getChangeOperationId()))
            && (this.getRepositoryId() == null ? other.getRepositoryId() == null : this.getRepositoryId().equals(other.getRepositoryId()))
            && (this.getCommitId() == null ? other.getCommitId() == null : this.getCommitId().equals(other.getCommitId()))
            && (this.getFileName() == null ? other.getFileName() == null : this.getFileName().equals(other.getFileName()))
            && (this.getRootEntityType() == null ? other.getRootEntityType() == null : this.getRootEntityType().equals(other.getRootEntityType()))
            && (this.getParentEntityType() == null ? other.getParentEntityType() == null : this.getParentEntityType().equals(other.getParentEntityType()))
            && (this.getChangeType() == null ? other.getChangeType() == null : this.getChangeType().equals(other.getChangeType()))
            && (this.getSignificanceLevel() == null ? other.getSignificanceLevel() == null : this.getSignificanceLevel().equals(other.getSignificanceLevel()))
            && (this.getChangedEntityType() == null ? other.getChangedEntityType() == null : this.getChangedEntityType().equals(other.getChangedEntityType()))
            && (this.getRootEntityContent() == null ? other.getRootEntityContent() == null : this.getRootEntityContent().equals(other.getRootEntityContent()))
            && (this.getParentEntityContent() == null ? other.getParentEntityContent() == null : this.getParentEntityContent().equals(other.getParentEntityContent()))
            && (this.getChangedEntityContent() == null ? other.getChangedEntityContent() == null : this.getChangedEntityContent().equals(other.getChangedEntityContent()))
            && (this.getNewEntityContent() == null ? other.getNewEntityContent() == null : this.getNewEntityContent().equals(other.getNewEntityContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_operation
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getChangeOperationId() == null) ? 0 : getChangeOperationId().hashCode());
        result = prime * result + ((getRepositoryId() == null) ? 0 : getRepositoryId().hashCode());
        result = prime * result + ((getCommitId() == null) ? 0 : getCommitId().hashCode());
        result = prime * result + ((getFileName() == null) ? 0 : getFileName().hashCode());
        result = prime * result + ((getRootEntityType() == null) ? 0 : getRootEntityType().hashCode());
        result = prime * result + ((getParentEntityType() == null) ? 0 : getParentEntityType().hashCode());
        result = prime * result + ((getChangeType() == null) ? 0 : getChangeType().hashCode());
        result = prime * result + ((getSignificanceLevel() == null) ? 0 : getSignificanceLevel().hashCode());
        result = prime * result + ((getChangedEntityType() == null) ? 0 : getChangedEntityType().hashCode());
        result = prime * result + ((getRootEntityContent() == null) ? 0 : getRootEntityContent().hashCode());
        result = prime * result + ((getParentEntityContent() == null) ? 0 : getParentEntityContent().hashCode());
        result = prime * result + ((getChangedEntityContent() == null) ? 0 : getChangedEntityContent().hashCode());
        result = prime * result + ((getNewEntityContent() == null) ? 0 : getNewEntityContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_operation
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rootEntityContent=").append(rootEntityContent);
        sb.append(", parentEntityContent=").append(parentEntityContent);
        sb.append(", changedEntityContent=").append(changedEntityContent);
        sb.append(", newEntityContent=").append(newEntityContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}