package cn.edu.fudan.se.cochange_analysis.git.bean;

import java.io.Serializable;

public class ChangeRelationCount implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_relation_count.change_relation_count_id
     *
     * @mbg.generated
     */
    private Integer changeRelationCountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_relation_count.repository_id
     *
     * @mbg.generated
     */
    private Integer repositoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_relation_count.file_name1
     *
     * @mbg.generated
     */
    private String fileName1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_relation_count.file_name2
     *
     * @mbg.generated
     */
    private String fileName2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_relation_count.change_type1
     *
     * @mbg.generated
     */
    private String changeType1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_relation_count.changed_entity_type1
     *
     * @mbg.generated
     */
    private String changedEntityType1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_relation_count.change_type2
     *
     * @mbg.generated
     */
    private String changeType2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_relation_count.changed_entity_type2
     *
     * @mbg.generated
     */
    private String changedEntityType2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_relation_count.count
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table change_relation_count
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_relation_count
     *
     * @mbg.generated
     */
    public ChangeRelationCount(Integer changeRelationCountId, Integer repositoryId, String fileName1, String fileName2, String changeType1, String changedEntityType1, String changeType2, String changedEntityType2, Integer count) {
        this.changeRelationCountId = changeRelationCountId;
        this.repositoryId = repositoryId;
        this.fileName1 = fileName1;
        this.fileName2 = fileName2;
        this.changeType1 = changeType1;
        this.changedEntityType1 = changedEntityType1;
        this.changeType2 = changeType2;
        this.changedEntityType2 = changedEntityType2;
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_relation_count
     *
     * @mbg.generated
     */
    public ChangeRelationCount() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_relation_count.change_relation_count_id
     *
     * @return the value of change_relation_count.change_relation_count_id
     *
     * @mbg.generated
     */
    public Integer getChangeRelationCountId() {
        return changeRelationCountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_relation_count.change_relation_count_id
     *
     * @param changeRelationCountId the value for change_relation_count.change_relation_count_id
     *
     * @mbg.generated
     */
    public void setChangeRelationCountId(Integer changeRelationCountId) {
        this.changeRelationCountId = changeRelationCountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_relation_count.repository_id
     *
     * @return the value of change_relation_count.repository_id
     *
     * @mbg.generated
     */
    public Integer getRepositoryId() {
        return repositoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_relation_count.repository_id
     *
     * @param repositoryId the value for change_relation_count.repository_id
     *
     * @mbg.generated
     */
    public void setRepositoryId(Integer repositoryId) {
        this.repositoryId = repositoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_relation_count.file_name1
     *
     * @return the value of change_relation_count.file_name1
     *
     * @mbg.generated
     */
    public String getFileName1() {
        return fileName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_relation_count.file_name1
     *
     * @param fileName1 the value for change_relation_count.file_name1
     *
     * @mbg.generated
     */
    public void setFileName1(String fileName1) {
        this.fileName1 = fileName1 == null ? null : fileName1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_relation_count.file_name2
     *
     * @return the value of change_relation_count.file_name2
     *
     * @mbg.generated
     */
    public String getFileName2() {
        return fileName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_relation_count.file_name2
     *
     * @param fileName2 the value for change_relation_count.file_name2
     *
     * @mbg.generated
     */
    public void setFileName2(String fileName2) {
        this.fileName2 = fileName2 == null ? null : fileName2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_relation_count.change_type1
     *
     * @return the value of change_relation_count.change_type1
     *
     * @mbg.generated
     */
    public String getChangeType1() {
        return changeType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_relation_count.change_type1
     *
     * @param changeType1 the value for change_relation_count.change_type1
     *
     * @mbg.generated
     */
    public void setChangeType1(String changeType1) {
        this.changeType1 = changeType1 == null ? null : changeType1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_relation_count.changed_entity_type1
     *
     * @return the value of change_relation_count.changed_entity_type1
     *
     * @mbg.generated
     */
    public String getChangedEntityType1() {
        return changedEntityType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_relation_count.changed_entity_type1
     *
     * @param changedEntityType1 the value for change_relation_count.changed_entity_type1
     *
     * @mbg.generated
     */
    public void setChangedEntityType1(String changedEntityType1) {
        this.changedEntityType1 = changedEntityType1 == null ? null : changedEntityType1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_relation_count.change_type2
     *
     * @return the value of change_relation_count.change_type2
     *
     * @mbg.generated
     */
    public String getChangeType2() {
        return changeType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_relation_count.change_type2
     *
     * @param changeType2 the value for change_relation_count.change_type2
     *
     * @mbg.generated
     */
    public void setChangeType2(String changeType2) {
        this.changeType2 = changeType2 == null ? null : changeType2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_relation_count.changed_entity_type2
     *
     * @return the value of change_relation_count.changed_entity_type2
     *
     * @mbg.generated
     */
    public String getChangedEntityType2() {
        return changedEntityType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_relation_count.changed_entity_type2
     *
     * @param changedEntityType2 the value for change_relation_count.changed_entity_type2
     *
     * @mbg.generated
     */
    public void setChangedEntityType2(String changedEntityType2) {
        this.changedEntityType2 = changedEntityType2 == null ? null : changedEntityType2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_relation_count.count
     *
     * @return the value of change_relation_count.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_relation_count.count
     *
     * @param count the value for change_relation_count.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_relation_count
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ChangeRelationCount other = (ChangeRelationCount) that;
        return (this.getChangeRelationCountId() == null ? other.getChangeRelationCountId() == null : this.getChangeRelationCountId().equals(other.getChangeRelationCountId()))
            && (this.getRepositoryId() == null ? other.getRepositoryId() == null : this.getRepositoryId().equals(other.getRepositoryId()))
            && (this.getFileName1() == null ? other.getFileName1() == null : this.getFileName1().equals(other.getFileName1()))
            && (this.getFileName2() == null ? other.getFileName2() == null : this.getFileName2().equals(other.getFileName2()))
            && (this.getChangeType1() == null ? other.getChangeType1() == null : this.getChangeType1().equals(other.getChangeType1()))
            && (this.getChangedEntityType1() == null ? other.getChangedEntityType1() == null : this.getChangedEntityType1().equals(other.getChangedEntityType1()))
            && (this.getChangeType2() == null ? other.getChangeType2() == null : this.getChangeType2().equals(other.getChangeType2()))
            && (this.getChangedEntityType2() == null ? other.getChangedEntityType2() == null : this.getChangedEntityType2().equals(other.getChangedEntityType2()))
            && (this.getCount() == null ? other.getCount() == null : this.getCount().equals(other.getCount()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_relation_count
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getChangeRelationCountId() == null) ? 0 : getChangeRelationCountId().hashCode());
        result = prime * result + ((getRepositoryId() == null) ? 0 : getRepositoryId().hashCode());
        result = prime * result + ((getFileName1() == null) ? 0 : getFileName1().hashCode());
        result = prime * result + ((getFileName2() == null) ? 0 : getFileName2().hashCode());
        result = prime * result + ((getChangeType1() == null) ? 0 : getChangeType1().hashCode());
        result = prime * result + ((getChangedEntityType1() == null) ? 0 : getChangedEntityType1().hashCode());
        result = prime * result + ((getChangeType2() == null) ? 0 : getChangeType2().hashCode());
        result = prime * result + ((getChangedEntityType2() == null) ? 0 : getChangedEntityType2().hashCode());
        result = prime * result + ((getCount() == null) ? 0 : getCount().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_relation_count
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", changeRelationCountId=").append(changeRelationCountId);
        sb.append(", repositoryId=").append(repositoryId);
        sb.append(", fileName1=").append(fileName1);
        sb.append(", fileName2=").append(fileName2);
        sb.append(", changeType1=").append(changeType1);
        sb.append(", changedEntityType1=").append(changedEntityType1);
        sb.append(", changeType2=").append(changeType2);
        sb.append(", changedEntityType2=").append(changedEntityType2);
        sb.append(", count=").append(count);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}