package cn.edu.fudan.se.cochange_analysis.git.bean;

import java.io.Serializable;

public class ClusterAncestor implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster_ancestor.cluster_threshold_id
     *
     * @mbg.generated
     */
    private Integer clusterThresholdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster_ancestor.repository_id
     *
     * @mbg.generated
     */
    private Integer repositoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster_ancestor.cluster_id
     *
     * @mbg.generated
     */
    private Integer clusterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster_ancestor.ancestor_id
     *
     * @mbg.generated
     */
    private Integer ancestorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cluster_ancestor.ancestor_type
     *
     * @mbg.generated
     */
    private Integer ancestorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cluster_ancestor
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_ancestor
     *
     * @mbg.generated
     */
    public ClusterAncestor(Integer clusterThresholdId, Integer repositoryId, Integer clusterId, Integer ancestorId, Integer ancestorType) {
        this.clusterThresholdId = clusterThresholdId;
        this.repositoryId = repositoryId;
        this.clusterId = clusterId;
        this.ancestorId = ancestorId;
        this.ancestorType = ancestorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_ancestor
     *
     * @mbg.generated
     */
    public ClusterAncestor() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster_ancestor.cluster_threshold_id
     *
     * @return the value of cluster_ancestor.cluster_threshold_id
     *
     * @mbg.generated
     */
    public Integer getClusterThresholdId() {
        return clusterThresholdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cluster_ancestor.cluster_threshold_id
     *
     * @param clusterThresholdId the value for cluster_ancestor.cluster_threshold_id
     *
     * @mbg.generated
     */
    public void setClusterThresholdId(Integer clusterThresholdId) {
        this.clusterThresholdId = clusterThresholdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster_ancestor.repository_id
     *
     * @return the value of cluster_ancestor.repository_id
     *
     * @mbg.generated
     */
    public Integer getRepositoryId() {
        return repositoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cluster_ancestor.repository_id
     *
     * @param repositoryId the value for cluster_ancestor.repository_id
     *
     * @mbg.generated
     */
    public void setRepositoryId(Integer repositoryId) {
        this.repositoryId = repositoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster_ancestor.cluster_id
     *
     * @return the value of cluster_ancestor.cluster_id
     *
     * @mbg.generated
     */
    public Integer getClusterId() {
        return clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cluster_ancestor.cluster_id
     *
     * @param clusterId the value for cluster_ancestor.cluster_id
     *
     * @mbg.generated
     */
    public void setClusterId(Integer clusterId) {
        this.clusterId = clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster_ancestor.ancestor_id
     *
     * @return the value of cluster_ancestor.ancestor_id
     *
     * @mbg.generated
     */
    public Integer getAncestorId() {
        return ancestorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cluster_ancestor.ancestor_id
     *
     * @param ancestorId the value for cluster_ancestor.ancestor_id
     *
     * @mbg.generated
     */
    public void setAncestorId(Integer ancestorId) {
        this.ancestorId = ancestorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cluster_ancestor.ancestor_type
     *
     * @return the value of cluster_ancestor.ancestor_type
     *
     * @mbg.generated
     */
    public Integer getAncestorType() {
        return ancestorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cluster_ancestor.ancestor_type
     *
     * @param ancestorType the value for cluster_ancestor.ancestor_type
     *
     * @mbg.generated
     */
    public void setAncestorType(Integer ancestorType) {
        this.ancestorType = ancestorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_ancestor
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ClusterAncestor other = (ClusterAncestor) that;
        return (this.getClusterThresholdId() == null ? other.getClusterThresholdId() == null : this.getClusterThresholdId().equals(other.getClusterThresholdId()))
            && (this.getRepositoryId() == null ? other.getRepositoryId() == null : this.getRepositoryId().equals(other.getRepositoryId()))
            && (this.getClusterId() == null ? other.getClusterId() == null : this.getClusterId().equals(other.getClusterId()))
            && (this.getAncestorId() == null ? other.getAncestorId() == null : this.getAncestorId().equals(other.getAncestorId()))
            && (this.getAncestorType() == null ? other.getAncestorType() == null : this.getAncestorType().equals(other.getAncestorType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_ancestor
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getClusterThresholdId() == null) ? 0 : getClusterThresholdId().hashCode());
        result = prime * result + ((getRepositoryId() == null) ? 0 : getRepositoryId().hashCode());
        result = prime * result + ((getClusterId() == null) ? 0 : getClusterId().hashCode());
        result = prime * result + ((getAncestorId() == null) ? 0 : getAncestorId().hashCode());
        result = prime * result + ((getAncestorType() == null) ? 0 : getAncestorType().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_ancestor
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", clusterThresholdId=").append(clusterThresholdId);
        sb.append(", repositoryId=").append(repositoryId);
        sb.append(", clusterId=").append(clusterId);
        sb.append(", ancestorId=").append(ancestorId);
        sb.append(", ancestorType=").append(ancestorType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}