package cn.edu.fudan.se.cochange_analysis.git.bean;

import java.io.Serializable;
import java.util.Date;

public class Commit extends CommitKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commit.short_message
     *
     * @mbg.generated
     */
    private String shortMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commit.full_message
     *
     * @mbg.generated
     */
    private String fullMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commit.author_name
     *
     * @mbg.generated
     */
    private String authorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commit.author_email
     *
     * @mbg.generated
     */
    private String authorEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commit.authored_date
     *
     * @mbg.generated
     */
    private Date authoredDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commit.committer_name
     *
     * @mbg.generated
     */
    private String committerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commit.committer_email
     *
     * @mbg.generated
     */
    private String committerEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commit.committed_date
     *
     * @mbg.generated
     */
    private Date committedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commit
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit
     *
     * @mbg.generated
     */
    public Commit(Integer repositoryId, String commitId, String shortMessage, String fullMessage, String authorName, String authorEmail, Date authoredDate, String committerName, String committerEmail, Date committedDate) {
        super(repositoryId, commitId);
        this.shortMessage = shortMessage;
        this.fullMessage = fullMessage;
        this.authorName = authorName;
        this.authorEmail = authorEmail;
        this.authoredDate = authoredDate;
        this.committerName = committerName;
        this.committerEmail = committerEmail;
        this.committedDate = committedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit
     *
     * @mbg.generated
     */
    public Commit() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commit.short_message
     *
     * @return the value of commit.short_message
     *
     * @mbg.generated
     */
    public String getShortMessage() {
        return shortMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commit.short_message
     *
     * @param shortMessage the value for commit.short_message
     *
     * @mbg.generated
     */
    public void setShortMessage(String shortMessage) {
        this.shortMessage = shortMessage == null ? null : shortMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commit.full_message
     *
     * @return the value of commit.full_message
     *
     * @mbg.generated
     */
    public String getFullMessage() {
        return fullMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commit.full_message
     *
     * @param fullMessage the value for commit.full_message
     *
     * @mbg.generated
     */
    public void setFullMessage(String fullMessage) {
        this.fullMessage = fullMessage == null ? null : fullMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commit.author_name
     *
     * @return the value of commit.author_name
     *
     * @mbg.generated
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commit.author_name
     *
     * @param authorName the value for commit.author_name
     *
     * @mbg.generated
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName == null ? null : authorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commit.author_email
     *
     * @return the value of commit.author_email
     *
     * @mbg.generated
     */
    public String getAuthorEmail() {
        return authorEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commit.author_email
     *
     * @param authorEmail the value for commit.author_email
     *
     * @mbg.generated
     */
    public void setAuthorEmail(String authorEmail) {
        this.authorEmail = authorEmail == null ? null : authorEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commit.authored_date
     *
     * @return the value of commit.authored_date
     *
     * @mbg.generated
     */
    public Date getAuthoredDate() {
        return authoredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commit.authored_date
     *
     * @param authoredDate the value for commit.authored_date
     *
     * @mbg.generated
     */
    public void setAuthoredDate(Date authoredDate) {
        this.authoredDate = authoredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commit.committer_name
     *
     * @return the value of commit.committer_name
     *
     * @mbg.generated
     */
    public String getCommitterName() {
        return committerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commit.committer_name
     *
     * @param committerName the value for commit.committer_name
     *
     * @mbg.generated
     */
    public void setCommitterName(String committerName) {
        this.committerName = committerName == null ? null : committerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commit.committer_email
     *
     * @return the value of commit.committer_email
     *
     * @mbg.generated
     */
    public String getCommitterEmail() {
        return committerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commit.committer_email
     *
     * @param committerEmail the value for commit.committer_email
     *
     * @mbg.generated
     */
    public void setCommitterEmail(String committerEmail) {
        this.committerEmail = committerEmail == null ? null : committerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commit.committed_date
     *
     * @return the value of commit.committed_date
     *
     * @mbg.generated
     */
    public Date getCommittedDate() {
        return committedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commit.committed_date
     *
     * @param committedDate the value for commit.committed_date
     *
     * @mbg.generated
     */
    public void setCommittedDate(Date committedDate) {
        this.committedDate = committedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Commit other = (Commit) that;
        return (this.getRepositoryId() == null ? other.getRepositoryId() == null : this.getRepositoryId().equals(other.getRepositoryId()))
            && (this.getCommitId() == null ? other.getCommitId() == null : this.getCommitId().equals(other.getCommitId()))
            && (this.getShortMessage() == null ? other.getShortMessage() == null : this.getShortMessage().equals(other.getShortMessage()))
            && (this.getFullMessage() == null ? other.getFullMessage() == null : this.getFullMessage().equals(other.getFullMessage()))
            && (this.getAuthorName() == null ? other.getAuthorName() == null : this.getAuthorName().equals(other.getAuthorName()))
            && (this.getAuthorEmail() == null ? other.getAuthorEmail() == null : this.getAuthorEmail().equals(other.getAuthorEmail()))
            && (this.getAuthoredDate() == null ? other.getAuthoredDate() == null : this.getAuthoredDate().equals(other.getAuthoredDate()))
            && (this.getCommitterName() == null ? other.getCommitterName() == null : this.getCommitterName().equals(other.getCommitterName()))
            && (this.getCommitterEmail() == null ? other.getCommitterEmail() == null : this.getCommitterEmail().equals(other.getCommitterEmail()))
            && (this.getCommittedDate() == null ? other.getCommittedDate() == null : this.getCommittedDate().equals(other.getCommittedDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRepositoryId() == null) ? 0 : getRepositoryId().hashCode());
        result = prime * result + ((getCommitId() == null) ? 0 : getCommitId().hashCode());
        result = prime * result + ((getShortMessage() == null) ? 0 : getShortMessage().hashCode());
        result = prime * result + ((getFullMessage() == null) ? 0 : getFullMessage().hashCode());
        result = prime * result + ((getAuthorName() == null) ? 0 : getAuthorName().hashCode());
        result = prime * result + ((getAuthorEmail() == null) ? 0 : getAuthorEmail().hashCode());
        result = prime * result + ((getAuthoredDate() == null) ? 0 : getAuthoredDate().hashCode());
        result = prime * result + ((getCommitterName() == null) ? 0 : getCommitterName().hashCode());
        result = prime * result + ((getCommitterEmail() == null) ? 0 : getCommitterEmail().hashCode());
        result = prime * result + ((getCommittedDate() == null) ? 0 : getCommittedDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", shortMessage=").append(shortMessage);
        sb.append(", fullMessage=").append(fullMessage);
        sb.append(", authorName=").append(authorName);
        sb.append(", authorEmail=").append(authorEmail);
        sb.append(", authoredDate=").append(authoredDate);
        sb.append(", committerName=").append(committerName);
        sb.append(", committerEmail=").append(committerEmail);
        sb.append(", committedDate=").append(committedDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}