package cn.edu.fudan.se.cochange_analysis.git.bean;

import java.io.Serializable;

public class FilePairCommit extends FilePairCommitKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_pair_commit.file_pair
     *
     * @mbg.generated
     */
    private String filePair;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_pair_commit
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_commit
     *
     * @mbg.generated
     */
    public FilePairCommit(Integer repositoryId, String commitId, String fileName1, String fileName2, String filePair) {
        super(repositoryId, commitId, fileName1, fileName2);
        this.filePair = filePair;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_commit
     *
     * @mbg.generated
     */
    public FilePairCommit() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_pair_commit.file_pair
     *
     * @return the value of file_pair_commit.file_pair
     *
     * @mbg.generated
     */
    public String getFilePair() {
        return filePair;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_pair_commit.file_pair
     *
     * @param filePair the value for file_pair_commit.file_pair
     *
     * @mbg.generated
     */
    public void setFilePair(String filePair) {
        this.filePair = filePair == null ? null : filePair.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_commit
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FilePairCommit other = (FilePairCommit) that;
        return (this.getRepositoryId() == null ? other.getRepositoryId() == null : this.getRepositoryId().equals(other.getRepositoryId()))
            && (this.getCommitId() == null ? other.getCommitId() == null : this.getCommitId().equals(other.getCommitId()))
            && (this.getFileName1() == null ? other.getFileName1() == null : this.getFileName1().equals(other.getFileName1()))
            && (this.getFileName2() == null ? other.getFileName2() == null : this.getFileName2().equals(other.getFileName2()))
            && (this.getFilePair() == null ? other.getFilePair() == null : this.getFilePair().equals(other.getFilePair()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_commit
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRepositoryId() == null) ? 0 : getRepositoryId().hashCode());
        result = prime * result + ((getCommitId() == null) ? 0 : getCommitId().hashCode());
        result = prime * result + ((getFileName1() == null) ? 0 : getFileName1().hashCode());
        result = prime * result + ((getFileName2() == null) ? 0 : getFileName2().hashCode());
        result = prime * result + ((getFilePair() == null) ? 0 : getFilePair().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_commit
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", filePair=").append(filePair);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}