package cn.edu.fudan.se.cochange_analysis.git.bean;

import java.io.Serializable;

public class FilePairCommitKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_pair_commit.repository_id
     *
     * @mbg.generated
     */
    private Integer repositoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_pair_commit.commit_id
     *
     * @mbg.generated
     */
    private String commitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_pair_commit.file_name1
     *
     * @mbg.generated
     */
    private String fileName1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_pair_commit.file_name2
     *
     * @mbg.generated
     */
    private String fileName2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_pair_commit
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_commit
     *
     * @mbg.generated
     */
    public FilePairCommitKey(Integer repositoryId, String commitId, String fileName1, String fileName2) {
        this.repositoryId = repositoryId;
        this.commitId = commitId;
        this.fileName1 = fileName1;
        this.fileName2 = fileName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_commit
     *
     * @mbg.generated
     */
    public FilePairCommitKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_pair_commit.repository_id
     *
     * @return the value of file_pair_commit.repository_id
     *
     * @mbg.generated
     */
    public Integer getRepositoryId() {
        return repositoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_pair_commit.repository_id
     *
     * @param repositoryId the value for file_pair_commit.repository_id
     *
     * @mbg.generated
     */
    public void setRepositoryId(Integer repositoryId) {
        this.repositoryId = repositoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_pair_commit.commit_id
     *
     * @return the value of file_pair_commit.commit_id
     *
     * @mbg.generated
     */
    public String getCommitId() {
        return commitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_pair_commit.commit_id
     *
     * @param commitId the value for file_pair_commit.commit_id
     *
     * @mbg.generated
     */
    public void setCommitId(String commitId) {
        this.commitId = commitId == null ? null : commitId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_pair_commit.file_name1
     *
     * @return the value of file_pair_commit.file_name1
     *
     * @mbg.generated
     */
    public String getFileName1() {
        return fileName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_pair_commit.file_name1
     *
     * @param fileName1 the value for file_pair_commit.file_name1
     *
     * @mbg.generated
     */
    public void setFileName1(String fileName1) {
        this.fileName1 = fileName1 == null ? null : fileName1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_pair_commit.file_name2
     *
     * @return the value of file_pair_commit.file_name2
     *
     * @mbg.generated
     */
    public String getFileName2() {
        return fileName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_pair_commit.file_name2
     *
     * @param fileName2 the value for file_pair_commit.file_name2
     *
     * @mbg.generated
     */
    public void setFileName2(String fileName2) {
        this.fileName2 = fileName2 == null ? null : fileName2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_commit
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FilePairCommitKey other = (FilePairCommitKey) that;
        return (this.getRepositoryId() == null ? other.getRepositoryId() == null : this.getRepositoryId().equals(other.getRepositoryId()))
            && (this.getCommitId() == null ? other.getCommitId() == null : this.getCommitId().equals(other.getCommitId()))
            && (this.getFileName1() == null ? other.getFileName1() == null : this.getFileName1().equals(other.getFileName1()))
            && (this.getFileName2() == null ? other.getFileName2() == null : this.getFileName2().equals(other.getFileName2()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_commit
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRepositoryId() == null) ? 0 : getRepositoryId().hashCode());
        result = prime * result + ((getCommitId() == null) ? 0 : getCommitId().hashCode());
        result = prime * result + ((getFileName1() == null) ? 0 : getFileName1().hashCode());
        result = prime * result + ((getFileName2() == null) ? 0 : getFileName2().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_commit
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", repositoryId=").append(repositoryId);
        sb.append(", commitId=").append(commitId);
        sb.append(", fileName1=").append(fileName1);
        sb.append(", fileName2=").append(fileName2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}