package cn.edu.fudan.se.cochange_analysis.git.bean;

import java.io.Serializable;

public class Hotspot implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotspot.cluster_threshold_id
     *
     * @mbg.generated
     */
    private Integer clusterThresholdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotspot.hotspot_threshold_id
     *
     * @mbg.generated
     */
    private Integer hotspotThresholdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotspot.repository_id
     *
     * @mbg.generated
     */
    private Integer repositoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotspot.cluster_id
     *
     * @mbg.generated
     */
    private Integer clusterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotspot
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot
     *
     * @mbg.generated
     */
    public Hotspot(Integer clusterThresholdId, Integer hotspotThresholdId, Integer repositoryId, Integer clusterId) {
        this.clusterThresholdId = clusterThresholdId;
        this.hotspotThresholdId = hotspotThresholdId;
        this.repositoryId = repositoryId;
        this.clusterId = clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot
     *
     * @mbg.generated
     */
    public Hotspot() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotspot.cluster_threshold_id
     *
     * @return the value of hotspot.cluster_threshold_id
     *
     * @mbg.generated
     */
    public Integer getClusterThresholdId() {
        return clusterThresholdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotspot.cluster_threshold_id
     *
     * @param clusterThresholdId the value for hotspot.cluster_threshold_id
     *
     * @mbg.generated
     */
    public void setClusterThresholdId(Integer clusterThresholdId) {
        this.clusterThresholdId = clusterThresholdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotspot.hotspot_threshold_id
     *
     * @return the value of hotspot.hotspot_threshold_id
     *
     * @mbg.generated
     */
    public Integer getHotspotThresholdId() {
        return hotspotThresholdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotspot.hotspot_threshold_id
     *
     * @param hotspotThresholdId the value for hotspot.hotspot_threshold_id
     *
     * @mbg.generated
     */
    public void setHotspotThresholdId(Integer hotspotThresholdId) {
        this.hotspotThresholdId = hotspotThresholdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotspot.repository_id
     *
     * @return the value of hotspot.repository_id
     *
     * @mbg.generated
     */
    public Integer getRepositoryId() {
        return repositoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotspot.repository_id
     *
     * @param repositoryId the value for hotspot.repository_id
     *
     * @mbg.generated
     */
    public void setRepositoryId(Integer repositoryId) {
        this.repositoryId = repositoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotspot.cluster_id
     *
     * @return the value of hotspot.cluster_id
     *
     * @mbg.generated
     */
    public Integer getClusterId() {
        return clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotspot.cluster_id
     *
     * @param clusterId the value for hotspot.cluster_id
     *
     * @mbg.generated
     */
    public void setClusterId(Integer clusterId) {
        this.clusterId = clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Hotspot other = (Hotspot) that;
        return (this.getClusterThresholdId() == null ? other.getClusterThresholdId() == null : this.getClusterThresholdId().equals(other.getClusterThresholdId()))
            && (this.getHotspotThresholdId() == null ? other.getHotspotThresholdId() == null : this.getHotspotThresholdId().equals(other.getHotspotThresholdId()))
            && (this.getRepositoryId() == null ? other.getRepositoryId() == null : this.getRepositoryId().equals(other.getRepositoryId()))
            && (this.getClusterId() == null ? other.getClusterId() == null : this.getClusterId().equals(other.getClusterId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getClusterThresholdId() == null) ? 0 : getClusterThresholdId().hashCode());
        result = prime * result + ((getHotspotThresholdId() == null) ? 0 : getHotspotThresholdId().hashCode());
        result = prime * result + ((getRepositoryId() == null) ? 0 : getRepositoryId().hashCode());
        result = prime * result + ((getClusterId() == null) ? 0 : getClusterId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", clusterThresholdId=").append(clusterThresholdId);
        sb.append(", hotspotThresholdId=").append(hotspotThresholdId);
        sb.append(", repositoryId=").append(repositoryId);
        sb.append(", clusterId=").append(clusterId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}