package cn.edu.fudan.se.cochange_analysis.git.bean;

import java.io.Serializable;

public class Repository implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.repository_id
     *
     * @mbg.generated
     */
    private Integer repositoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.repository_name
     *
     * @mbg.generated
     */
    private String repositoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.repository_path
     *
     * @mbg.generated
     */
    private String repositoryPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table repository
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbg.generated
     */
    public Repository(Integer repositoryId, String repositoryName, String repositoryPath) {
        this.repositoryId = repositoryId;
        this.repositoryName = repositoryName;
        this.repositoryPath = repositoryPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbg.generated
     */
    public Repository() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.repository_id
     *
     * @return the value of repository.repository_id
     *
     * @mbg.generated
     */
    public Integer getRepositoryId() {
        return repositoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.repository_id
     *
     * @param repositoryId the value for repository.repository_id
     *
     * @mbg.generated
     */
    public void setRepositoryId(Integer repositoryId) {
        this.repositoryId = repositoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.repository_name
     *
     * @return the value of repository.repository_name
     *
     * @mbg.generated
     */
    public String getRepositoryName() {
        return repositoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.repository_name
     *
     * @param repositoryName the value for repository.repository_name
     *
     * @mbg.generated
     */
    public void setRepositoryName(String repositoryName) {
        this.repositoryName = repositoryName == null ? null : repositoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.repository_path
     *
     * @return the value of repository.repository_path
     *
     * @mbg.generated
     */
    public String getRepositoryPath() {
        return repositoryPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.repository_path
     *
     * @param repositoryPath the value for repository.repository_path
     *
     * @mbg.generated
     */
    public void setRepositoryPath(String repositoryPath) {
        this.repositoryPath = repositoryPath == null ? null : repositoryPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Repository other = (Repository) that;
        return (this.getRepositoryId() == null ? other.getRepositoryId() == null : this.getRepositoryId().equals(other.getRepositoryId()))
            && (this.getRepositoryName() == null ? other.getRepositoryName() == null : this.getRepositoryName().equals(other.getRepositoryName()))
            && (this.getRepositoryPath() == null ? other.getRepositoryPath() == null : this.getRepositoryPath().equals(other.getRepositoryPath()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRepositoryId() == null) ? 0 : getRepositoryId().hashCode());
        result = prime * result + ((getRepositoryName() == null) ? 0 : getRepositoryName().hashCode());
        result = prime * result + ((getRepositoryPath() == null) ? 0 : getRepositoryPath().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", repositoryId=").append(repositoryId);
        sb.append(", repositoryName=").append(repositoryName);
        sb.append(", repositoryPath=").append(repositoryPath);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}