package cn.edu.fudan.se.cochange_analysis.git.dao;

import java.util.List;

import cn.edu.fudan.se.cochange_analysis.git.bean.BugFixFile;
import cn.edu.fudan.se.cochange_analysis.git.bean.BugFixFileKey;

public interface BugFixFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bug_fix_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BugFixFileKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bug_fix_file
     *
     * @mbg.generated
     */
    int insert(BugFixFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bug_fix_file
     *
     * @mbg.generated
     */
    int insertSelective(BugFixFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bug_fix_file
     *
     * @mbg.generated
     */
    BugFixFile selectByPrimaryKey(BugFixFileKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bug_fix_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BugFixFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bug_fix_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BugFixFile record);

	int insertBatch(List<BugFixFile> bugFixFileList);
}