package cn.edu.fudan.se.cochange_analysis.git.dao;

import cn.edu.fudan.se.cochange_analysis.git.bean.ChangeRelationCommitKey;

public interface ChangeRelationCommitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_relation_commit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(ChangeRelationCommitKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_relation_commit
     *
     * @mbg.generated
     */
    int insert(ChangeRelationCommitKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_relation_commit
     *
     * @mbg.generated
     */
    int insertSelective(ChangeRelationCommitKey record);
}