package cn.edu.fudan.se.cochange_analysis.git.dao;

import cn.edu.fudan.se.cochange_analysis.git.bean.ChangeRelationCommit;

public interface ChangeRelationCommitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_relation_commit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer changeRelationCommitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_relation_commit
     *
     * @mbg.generated
     */
    int insert(ChangeRelationCommit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_relation_commit
     *
     * @mbg.generated
     */
    int insertSelective(ChangeRelationCommit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_relation_commit
     *
     * @mbg.generated
     */
    ChangeRelationCommit selectByPrimaryKey(Integer changeRelationCommitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_relation_commit
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChangeRelationCommit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_relation_commit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChangeRelationCommit record);
}