package cn.edu.fudan.se.cochange_analysis.git.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.edu.fudan.se.cochange_analysis.git.bean.ChangeRelationCount;
import cn.edu.fudan.se.cochange_analysis.git.bean.ChangeRelationSum;

public interface ChangeRelationSumMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table change_relation_sum
	 *
	 * @mbg.generated
	 */
	int insert(ChangeRelationSum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table change_relation_sum
	 *
	 * @mbg.generated
	 */
	int insertSelective(ChangeRelationSum record);

	List<ChangeRelationCount> selectTopNByRepositoryId(@Param(value = "n") int n,
			@Param(value = "repositoryId") int repositoryId);
}