package cn.edu.fudan.se.cochange_analysis.git.dao;

import cn.edu.fudan.se.cochange_analysis.git.bean.ChangeFile;
import cn.edu.fudan.se.cochange_analysis.git.bean.ChangeFileKey;

public interface ChangeFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(ChangeFileKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_file
     *
     * @mbg.generated
     */
    int insert(ChangeFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_file
     *
     * @mbg.generated
     */
    int insertSelective(ChangeFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_file
     *
     * @mbg.generated
     */
    ChangeFile selectByPrimaryKey(ChangeFileKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChangeFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChangeFile record);
}