package cn.edu.fudan.se.cochange_analysis.git.dao;

import java.util.List;

import cn.edu.fudan.se.cochange_analysis.git.bean.ClusterAncestor;

public interface ClusterAncestorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_ancestor
     *
     * @mbg.generated
     */
    int insert(ClusterAncestor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cluster_ancestor
     *
     * @mbg.generated
     */
    int insertSelective(ClusterAncestor record);

	void insertBatch(List<ClusterAncestor> clusterAncestorList);
}