package cn.edu.fudan.se.cochange_analysis.git.dao;

import cn.edu.fudan.se.cochange_analysis.git.bean.Commit;
import cn.edu.fudan.se.cochange_analysis.git.bean.CommitKey;

public interface CommitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(CommitKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit
     *
     * @mbg.generated
     */
    int insert(Commit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit
     *
     * @mbg.generated
     */
    int insertSelective(Commit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit
     *
     * @mbg.generated
     */
    Commit selectByPrimaryKey(CommitKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Commit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Commit record);
}