package cn.edu.fudan.se.cochange_analysis.git.dao;

import cn.edu.fudan.se.cochange_analysis.git.bean.CommitType;
import cn.edu.fudan.se.cochange_analysis.git.bean.CommitTypeKey;

public interface CommitTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(CommitTypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit_type
     *
     * @mbg.generated
     */
    int insert(CommitType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit_type
     *
     * @mbg.generated
     */
    int insertSelective(CommitType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit_type
     *
     * @mbg.generated
     */
    CommitType selectByPrimaryKey(CommitTypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CommitType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CommitType record);
}