package cn.edu.fudan.se.cochange_analysis.git.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.edu.fudan.se.cochange_analysis.git.bean.FilePairCommit;
import cn.edu.fudan.se.cochange_analysis.git.bean.FilePairCommitKey;

public interface FilePairCommitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_commit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(FilePairCommitKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_commit
     *
     * @mbg.generated
     */
    int insert(FilePairCommit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_commit
     *
     * @mbg.generated
     */
    int insertSelective(FilePairCommit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_commit
     *
     * @mbg.generated
     */
    FilePairCommit selectByPrimaryKey(FilePairCommitKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_commit
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FilePairCommit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_commit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FilePairCommit record);
    
    
    List<FilePairCommit> selectByFilePairName(@Param(value="filePair") String filePair,@Param(value="repoId")int repoId);
}