package cn.edu.fudan.se.cochange_analysis.git.dao;

import cn.edu.fudan.se.cochange_analysis.git.bean.FilePairCount;
import cn.edu.fudan.se.cochange_analysis.git.bean.FilePairCountKey;

public interface FilePairCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_count
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(FilePairCountKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_count
     *
     * @mbg.generated
     */
    int insert(FilePairCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_count
     *
     * @mbg.generated
     */
    int insertSelective(FilePairCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_count
     *
     * @mbg.generated
     */
    FilePairCount selectByPrimaryKey(FilePairCountKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_count
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FilePairCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_pair_count
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FilePairCount record);
}