package cn.edu.fudan.se.cochange_analysis.git.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.edu.fudan.se.cochange_analysis.git.bean.GitCommitParentKey;

public interface GitCommitParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit_parent
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(GitCommitParentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit_parent
     *
     * @mbg.generated
     */
    int insert(GitCommitParentKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit_parent
     *
     * @mbg.generated
     */
    int insertSelective(GitCommitParentKey record);

	List<GitCommitParentKey> selectByRepositoryIdAndCommitId(@Param("repositoryId") int repositoryId,@Param("commitId") String commitId);
}