package cn.edu.fudan.se.cochange_analysis.git.dao;

import cn.edu.fudan.se.cochange_analysis.git.bean.GitCommitType;
import cn.edu.fudan.se.cochange_analysis.git.bean.GitCommitTypeKey;

public interface GitCommitTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(GitCommitTypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit_type
     *
     * @mbg.generated
     */
    int insert(GitCommitType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit_type
     *
     * @mbg.generated
     */
    int insertSelective(GitCommitType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit_type
     *
     * @mbg.generated
     */
    GitCommitType selectByPrimaryKey(GitCommitTypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GitCommitType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GitCommitType record);
}