package cn.edu.fudan.se.cochange_analysis.git.dao;

import cn.edu.fudan.se.cochange_analysis.git.bean.GitChangeFile;
import cn.edu.fudan.se.cochange_analysis.git.bean.GitChangeFileKey;

public interface GitChangeFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(GitChangeFileKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_file
     *
     * @mbg.generated
     */
    int insert(GitChangeFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_file
     *
     * @mbg.generated
     */
    int insertSelective(GitChangeFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_file
     *
     * @mbg.generated
     */
    GitChangeFile selectByPrimaryKey(GitChangeFileKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GitChangeFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GitChangeFile record);
}