package cn.edu.fudan.se.cochange_analysis.git.dao;

import java.util.List;

import cn.edu.fudan.se.cochange_analysis.git.bean.GitCommit;
import cn.edu.fudan.se.cochange_analysis.git.bean.GitCommitKey;

public interface GitCommitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(GitCommitKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit
     *
     * @mbg.generated
     */
    int insert(GitCommit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit
     *
     * @mbg.generated
     */
    int insertSelective(GitCommit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit
     *
     * @mbg.generated
     */
    GitCommit selectByPrimaryKey(GitCommitKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GitCommit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GitCommit record);
    
    
    List<GitCommit> selectByRepositoryId(int repositoryId);

	int insertFilter(GitCommit commit);
}