package cn.edu.fudan.se.cochange_analysis.git.dao;

import cn.edu.fudan.se.cochange_analysis.git.bean.GitCommitParent;
import cn.edu.fudan.se.cochange_analysis.git.bean.GitCommitParentKey;

public interface GitCommitParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit_parent
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(GitCommitParentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit_parent
     *
     * @mbg.generated
     */
    int insert(GitCommitParent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit_parent
     *
     * @mbg.generated
     */
    int insertSelective(GitCommitParent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit_parent
     *
     * @mbg.generated
     */
    GitCommitParent selectByPrimaryKey(GitCommitParentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit_parent
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GitCommitParent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commit_parent
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GitCommitParent record);
}