package cn.edu.fudan.se.cochange_analysis.git.dao;

import java.util.List;

import cn.edu.fudan.se.cochange_analysis.git.bean.HotspotRelationSum;

public interface HotspotRelationSumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot_relation_sum
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer clusterThresholdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot_relation_sum
     *
     * @mbg.generated
     */
    int insert(HotspotRelationSum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot_relation_sum
     *
     * @mbg.generated
     */
    int insertSelective(HotspotRelationSum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot_relation_sum
     *
     * @mbg.generated
     */
    HotspotRelationSum selectByPrimaryKey(Integer clusterThresholdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot_relation_sum
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HotspotRelationSum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotspot_relation_sum
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HotspotRelationSum record);

	void insertBatch(List<HotspotRelationSum> hotspotRelationSumList);
}