package cn.edu.fudan.se.cochange_analysis.git.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.edu.fudan.se.cochange_analysis.git.bean.Hotspot;

public interface HotspotMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table hotspot
	 *
	 * @mbg.generated
	 */
	int insert(Hotspot record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table hotspot
	 *
	 * @mbg.generated
	 */
	int insertSelective(Hotspot record);

	List<Hotspot> selectByThresholds(@Param("repositoryId") int repositoryId,
			@Param("clusterThresholdId") int clusterThresholdId, @Param("hotspotThresholdId") int hotspotThresholdId);
}