package cn.edu.fudan.se.cochange_analysis.git.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.edu.fudan.se.cochange_analysis.git.bean.OriginCluster;

public interface OriginClusterMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table origin_cluster
	 *
	 * @mbg.generated
	 */
	int insert(OriginCluster record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table origin_cluster
	 *
	 * @mbg.generated
	 */
	int insertSelective(OriginCluster record);

	List<Integer> selectByClusterThresholdIdAndMinSizeAndMinRatio(@Param("repositoryId") int repositoryId,
			@Param("clusterThresholdId") int clusterThresholdId, @Param("minSize") double minSize,
			@Param("minRatio") double minRatio);

	List<OriginCluster> selectByRepositoryIdAndClusterThresholdIdAndClusterId(@Param("repositoryId") int repositoryId,
			@Param("clusterThresholdId") int clusterThresholdId, @Param("clusterId") int clusterId);

	List<OriginCluster> selectByClusterThresholdIdAndMaxSize(@Param("repositoryId") int repositoryId,
			@Param("clusterThresholdId") int clusterThresholdId, @Param("maxSize") int maxSize);

	void insertBatch(List<OriginCluster> originClusterList);
}