package cn.edu.fudan.se.cochange_analysis.git.dao;

import java.util.List;

import cn.edu.fudan.se.cochange_analysis.git.bean.ParallelChangeRelationCommit;

public interface ParallelChangeRelationCommitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parallel_change_relation_commit
     *
     * @mbg.generated
     */
    int insert(ParallelChangeRelationCommit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parallel_change_relation_commit
     *
     * @mbg.generated
     */
    int insertSelective(ParallelChangeRelationCommit record);

	int insertBatch(List<ParallelChangeRelationCommit> parallelChangeRelationCommitList);

	List<ParallelChangeRelationCommit> selectDistinctByRepositoryId(int repositoryId);

	List<ParallelChangeRelationCommit> selectByRepositoryId(int repositoryId);
}