package cn.edu.fudan.se.cochange_analysis.git.dao;

import java.util.List;

import cn.edu.fudan.se.cochange_analysis.git.bean.RawFilterSharedDependency;

public interface RawFilterSharedDependencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raw_filter_shared_dependency
     *
     * @mbg.generated
     */
    int insert(RawFilterSharedDependency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raw_filter_shared_dependency
     *
     * @mbg.generated
     */
    int insertSelective(RawFilterSharedDependency record);

	List<RawFilterSharedDependency> selectByRepositoryId(int repositoryId);
}