package cn.edu.fudan.se.cochange_analysis.git.dao;

import java.util.List;

import cn.edu.fudan.se.cochange_analysis.git.bean.RawParallelChangeRelationCommit;

public interface RawParallelChangeRelationCommitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raw_parallel_change_relation_commit
     *
     * @mbg.generated
     */
    int insert(RawParallelChangeRelationCommit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raw_parallel_change_relation_commit
     *
     * @mbg.generated
     */
    int insertSelective(RawParallelChangeRelationCommit record);

	List<RawParallelChangeRelationCommit> selectByRepositoryId(int repositoryId);
}