package cn.edu.fudan.se.cochange_analysis.git.dao;

import java.util.List;

import cn.edu.fudan.se.cochange_analysis.git.bean.SharedDependency;

public interface SharedDependencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shared_dependency
     *
     * @mbg.generated
     */
    int insert(SharedDependency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shared_dependency
     *
     * @mbg.generated
     */
    int insertSelective(SharedDependency record);

	List<SharedDependency> selectByRepositoryId(int repositoryId);

	int insertBatch(List<SharedDependency> sharedDependencyList);
}