package cn.edu.fudan.se.cochange_analysis.git.dao;

import cn.edu.fudan.se.cochange_analysis.git.bean.SnapshootFile;

public interface SnapshootFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snapshoot_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer repositoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snapshoot_file
     *
     * @mbg.generated
     */
    int insert(SnapshootFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snapshoot_file
     *
     * @mbg.generated
     */
    int insertSelective(SnapshootFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snapshoot_file
     *
     * @mbg.generated
     */
    SnapshootFile selectByPrimaryKey(Integer repositoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snapshoot_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SnapshootFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snapshoot_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SnapshootFile record);
}