package cn.edu.fudan.se.cochange_analysis.git.dao;

import java.util.List;

import cn.edu.fudan.se.cochange_analysis.git.bean.ChangeRelationCommit;
import cn.edu.fudan.se.cochange_analysis.git.bean.SnapshotFile;

public interface SnapshotFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snapshot_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer repositoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snapshot_file
     *
     * @mbg.generated
     */
    int insert(SnapshotFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snapshot_file
     *
     * @mbg.generated
     */
    int insertSelective(SnapshotFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snapshot_file
     *
     * @mbg.generated
     */
    SnapshotFile selectByPrimaryKey(Integer repositoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snapshot_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SnapshotFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snapshot_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SnapshotFile record);
    
    int insertBatch(List<SnapshotFile> snapshotFiles);
}