package cn.edu.fudan.se.cochange_analysis.git.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.edu.fudan.se.cochange_analysis.git.bean.SnapshotFile;

public interface SnapshotFileMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table snapshot_file
	 *
	 * @mbg.generated
	 */
	int insert(SnapshotFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table snapshot_file
	 *
	 * @mbg.generated
	 */
	int insertSelective(SnapshotFile record);

	int insertBatch(List<SnapshotFile> snapshotFile);

	List<String> selectFileByRepositoryIdAndRelease(@Param(value = "repositoryId") Integer repositoryId,
			@Param(value = "release") String release);

	List<String> selectFileByRepositoryId(Integer repositoryId);
}